version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_docker-compose
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    networks:
      - app_404
    depends_on:
      - wordpress1
      - wordpress2
      - app_node

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    expose:
      - "81"
    environment:
      APACHE_LISTEN_PORT: 81

      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_SCHEMA}
    networks:
      - app_404
      
  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    expose:
      - "82"
    environment:

      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_SCHEMA}
    networks:
      - app_404

  app_node:
    image: patrickbnu/app_node:latest
    container_name: app_node
    expose:
      - "3000"
    environment:

      NODE_DB_HOST: ${DB_HOST}
      NODE_DB_PORT: ${DB_PORT}
      NODE_DB_USER: ${DB_USER}
      NODE_DB_PASS: ${DB_PASSWORD}
      NODE_DB_SCHEMA: ${SYSTEMS_DB_SCHEMA}
    networks:
      - app_404


networks:
  app_404:
    driver: bridge

