FROM eclipse-temurin:11


copy ./target/mysql-springboot-docker-0.0.1-SNAPSHOT.jar mysql-springboot-docker-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "mysql-springboot-docker-0.0.1-SNAPSHOT.jar"]


expose 8080