version: '3'
services:
  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    expose:
      - "80"
      - "443"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_SCHEMA}
    networks:
      - app_404
      
  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    expose:
      - "80"
      - "443"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_SCHEMA}
    networks:
      - app_404

  app_node:
    build: 
      context: ./node  
      dockerfile: Dockerfile 
    container_name: app_node
    expose:
      - "3000"
    environment:
      NODE_DB_HOST: ${DB_HOST}
      NODE_DB_PORT: ${DB_PORT}
      NODE_DB_USER: ${DB_USER}
      NODE_DB_PASS: ${DB_PASSWORD}
      NODE_DB_SCHEMA: ${SYSTEMS_DB_SCHEMA}
    networks:
      - app_404

  app_java:
    image: patrickbnu/app_java:latest
    #build: 
    #  context: ./java  
    #  dockerfile: Dockerfile 
    container_name: app_java
    expose:
      - "8080"
    environment:
      JAVA_DB_HOST: ${DB_HOST}
      JAVA_DB_PORT: ${DB_PORT}
      JAVA_DB_USER: ${DB_USER}
      JAVA_DB_PASS: ${DB_PASSWORD}
      JAVA_DB_SCHEMA: ${SYSTEMS_DB_SCHEMA}
    networks:
      - app_404

  app_django:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: app_django
    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_SCHEMA: ${SYSTEMS_DB_SCHEMA}
      DJANGO_DB_USER: ${DB_USER}
      DJANGO_DB_PASS: ${DB_PASSWORD}
      DJANGO_DB_HOST: ${DB_HOST}
      DJANGO_DB_PORT: ${DB_PORT}
    networks:
      - app_404

  # certbot:
  #    image: certbot/certbot
  #    volumes:
  #      - ./data/certbot/conf:/etc/letsencrypt
  #      - ./data/certbot/www:/var/www/certbot 
  #    networks:
  #      - app_404

  nginx:
    build: 
      context: ./nginx  
      dockerfile: Dockerfile 
    container_name: nginx_docker-compose
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app_404
    depends_on:
      - wordpress1
      - wordpress2
      - app_node


networks:
  app_404:
    driver: bridge
